/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanels;

import excel.ProgramasExcel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTextField;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

/**
 *
 * @author Juan
 */
public class AnadirVariado extends javax.swing.JFrame {

    public String getjLabelProductor() {
        return jLabel.getText();
    }

    public void setjLabelProductor(String opcion) {
        this.jLabel.setText(opcion);
    }

    private String getValue;

    /**
     * Creates new form AnadirProductor
     */
    public void AnadirVariado(String opcion) {
        initComponents();
        setjLabelProductor(opcion);
        InicializarJDialog();
        OptimizarCodigo optimizarCodigo = new OptimizarCodigo();
        optimizarCodigo.OptimizarBotones(MENUButton, VOLVERButton, OKButton);
        OKButton e1 = new OKButton();
        MENUButton e2 = new MENUButton();
        VOLVERButton e3 = new VOLVERButton();
        OKButton.addActionListener(e1);
        MENUButton.addActionListener(e2);
        VOLVERButton.addActionListener(e3);

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PRODUCTORTextField = new javax.swing.JTextField();
        jLabel = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PRODUCTORTextField.setToolTipText("");


        jLabel.setToolTipText("");


        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 97, Short.MAX_VALUE)
                        .addComponent(jLabel)
                        .addGap(32, 32, 32)
                        .addComponent(PRODUCTORTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(MENUButton)
                        .addGap(93, 93, 93)
                        .addComponent(VOLVERButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OKButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRODUCTORTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MENUButton)
                    .addComponent(VOLVERButton)
                    .addComponent(OKButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//GEN-FIRST:event_PRODUCTORTextFieldActionPerformed
        // TODO add your handling code here:
//GEN-LAST:event_PRODUCTORTextFieldActionPerformed

//GEN-FIRST:event_MENUButtonActionPerformed
        // TODO add your handling code here:
//GEN-LAST:event_MENUButtonActionPerformed

    public void InicializarJDialog() {
        JLabel label = new JLabel(getjLabelProductor() + " añadido anteriormente");
        dialog.setLocationRelativeTo(null);
        dialog.setTitle(getjLabelProductor()+ " ya añadido");
        dialog.add(label);
        dialog.pack();
        dialog.setBounds(500, 500, 200, 100);
    }

    public class MENUButton implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e2) {
            MenuPrincipalFrame obj = new MenuPrincipalFrame();
            obj.setVisible(true);
            dispose();
        }

    }

    public class VOLVERButton implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e2) {
            MenuAnadirFrame obj = new MenuAnadirFrame();
            obj.setVisible(true);
            dispose();
        }

    }

    public class OKButton implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e1) {
            getValue = PRODUCTORTextField.getText();
            AnadirVariado obj = new AnadirVariado();
            ProgramasExcel programasExcel = new ProgramasExcel();
            try {
                if (!programasExcel.PerteneceNombreAHoja(getjLabelProductor(), getValue)) {
                    programasExcel.comprobarColumna(getjLabelProductor(), getValue);
                } else {
                    obj.setVisible(false);
                    dialog.setVisible(true);
                }
            } catch (IOException ex) {
                Logger.getLogger(AnadirVariado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidFormatException ex) {
                Logger.getLogger(AnadirVariado.class.getName()).log(Level.SEVERE, null, ex);
            }
            obj.AnadirVariado(getjLabelProductor());
            obj.setVisible(true);
            dispose();
        }

    }



    private JDialog dialog = new JDialog();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton MENUButton = new JButton();
    public JButton OKButton= new JButton();
    public JTextField PRODUCTORTextField = new JTextField();
    public JButton VOLVERButton = new JButton();
    private JLabel jLabel = new JLabel();
    // End of variables declaration//GEN-END:variables
}
