/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanels;

import excel.ProgramasExcel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

/**
 *
 * @author juan-
 */
public class EditarAnadirVariado extends javax.swing.JFrame {

    /**
     * Creates new form EditarVariado
     */
    public EditarAnadirVariado(String hoja, String palabra) {
        initComponents();
        opc = palabra.equalsIgnoreCase("");
        Menu e1 = new Menu();
        Volver e2 = new Volver();
        OK e3 = new OK();
        opcionHoja = hoja;
        opcionPalabra = palabra;
        jLabelOpcion.setText(hoja + ": ");
        jTextFieldEditar.setText(palabra);
        jButtonMenu.addActionListener(e1);
        jButtonVolver.addActionListener(e2);
        jButtonOK.addActionListener(e3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldEditar = new javax.swing.JTextField();
        jLabelOpcion = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabelOpcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButtonOK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonOK.setText("OK");

        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonVolver.setText("VOLVER");

        jButtonMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonMenu.setText("MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButtonMenu)
                .addGap(190, 190, 190)
                .addComponent(jButtonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabelOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonMenu)
                    .addComponent(jButtonOK))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public class Menu implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e1) {
            MenuPrincipalFrame obj = new MenuPrincipalFrame();
            obj.setVisible(true);
            dispose();
        }

    }

    public class Volver implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e2) {
            if (opc){
                MenuAnadirFrame obj = new MenuAnadirFrame();
                obj.setVisible(true);
                dispose();
            }else{
            MenuEditarEliminar obj = new MenuEditarEliminar(false);
            obj.setVisible(true);
            dispose();
        }
        }
    }

    public class OK implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e3) {

            ProgramasExcel programasExcel = new ProgramasExcel();
            if (jTextFieldEditar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(jPanel1, "Existe Algun Campo Vacío", "Error!", JOptionPane.ERROR_MESSAGE);
            } else {
                if (opc) {
                    try {
                        if (!programasExcel.PerteneceNombreAHoja(opcionHoja, jTextFieldEditar.getText())) {
                            programasExcel.comprobarColumna(opcionHoja, jTextFieldEditar.getText());
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(EditarAnadirVariado.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InvalidFormatException ex) {
                        Logger.getLogger(EditarAnadirVariado.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    MenuAnadirFrame obj = new MenuAnadirFrame();
                    obj.setVisible(true);
                    dispose();
                    JOptionPane.showMessageDialog(jPanel1, opcionHoja + " añadido correctamente", "Correcto", JOptionPane.INFORMATION_MESSAGE);
                } else {

                    try {
                        programasExcel.editarNombre(opcionHoja, opcionPalabra, jTextFieldEditar.getText());
                    } catch (IOException ex) {
                        Logger.getLogger(EditarAnadirVariado.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InvalidFormatException ex) {
                        Logger.getLogger(EditarAnadirVariado.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    MenuEditarEliminar obj = new MenuEditarEliminar(false);
                    obj.setVisible(true);
                    dispose();
                    JOptionPane.showMessageDialog(jPanel1, opcionHoja + " editado correctamente", "Correcto", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }

    private boolean opc;
    private String opcionHoja;
    private String opcionPalabra;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelOpcion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEditar;
    // End of variables declaration//GEN-END:variables
}
