/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanels;

import excel.ProgramasExcel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

/**
 *
 * @author juan-
 */
public class EditarVariado extends javax.swing.JFrame {

    /**
     * Creates new form EditarVariado
     */
    public EditarVariado(String hoja, String palabra) {
        initComponents();
        Menu e1 = new Menu();
        Volver e2 = new Volver();
        OK e3 = new OK();
        opcionHoja = hoja;
        opcionPalabra = palabra;
        jLabelOpcion.setText(hoja + ": ");
        jTextFieldEditar.setText(palabra);
        jButtonMenu.addActionListener(e1);
        jButtonVolver.addActionListener(e2);
        jButtonOK.addActionListener(e3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOpcion = new javax.swing.JLabel();
        jTextFieldEditar = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonOK.setText("OK");

        jButtonMenu.setText("MENU");

        jButtonVolver.setText("VOLVER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabelOpcion)
                .addGap(55, 55, 55)
                .addComponent(jTextFieldEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonMenu)
                .addGap(93, 93, 93)
                .addComponent(jButtonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOpcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonMenu)
                    .addComponent(jButtonVolver))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

        public class Menu implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e1) {
            MenuPrincipalFrame obj = new MenuPrincipalFrame();
            obj.setVisible(true);
            dispose();
        }

    }

    public class Volver implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e2) {
            MenuEliminar obj = new MenuEliminar(false);
            obj.setVisible(true);
            dispose();
        }

    }
    
        public class OK implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e3) {
            ProgramasExcel programasExcel = new ProgramasExcel();
            try {
                programasExcel.editarNombre(opcionHoja, opcionPalabra, jTextFieldEditar.getText());
            } catch (IOException ex) {
                Logger.getLogger(EditarVariado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidFormatException ex) {
                Logger.getLogger(EditarVariado.class.getName()).log(Level.SEVERE, null, ex);
            }
            MenuEliminar obj = new MenuEliminar(false);
            obj.setVisible(true);
            dispose();
        }

    }
    
    
    
private String opcionHoja;
private String opcionPalabra;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelOpcion;
    private javax.swing.JTextField jTextFieldEditar;
    // End of variables declaration//GEN-END:variables
}
