/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanels;

import excel.ProgramasExcel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

/**
 *
 * @author Juan
 */
public class MenuEditarEliminar extends JFrame {

    /**
     * Creates new form MenuEditar
     */
    public MenuEditarEliminar(Boolean opcion) {
        initComponents();
        opc = opcion;

        //TRUE ELIMINAR, FALSE EDITAR
        EditarNombrePeliculaSub e1 = new EditarNombrePeliculaSub();
        EditarGeneroSub e2 = new EditarGeneroSub();
        EditarDirectorSub e3 = new EditarDirectorSub();
        EditarPaisSub e4 = new EditarPaisSub();
        EditarProductorSub e5 = new EditarProductorSub();
        OKSub e6 = new OKSub();
        ListSelectionSub e7 = new ListSelectionSub();
        Lista.addListSelectionListener(e7);
        MENUButton e8 = new MENUButton();
	EditarPeliculaSub e9 = new EditarPeliculaSub();
        EditarNombrePelicula.addActionListener(e1);
        EditarGenero.addActionListener(e2);
        EditarDirector.addActionListener(e3);
        EditarPais.addActionListener(e4);
        EditarProductor.addActionListener(e5);
        okButton.addActionListener(e6);
        menuButton.addActionListener(e8);
        EditarPelicula.addActionListener(e9);
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        EditarNombrePelicula = new javax.swing.JButton();
        EditarPelicula = new javax.swing.JButton();
        EditarDirector = new javax.swing.JButton();
        EditarGenero = new javax.swing.JButton();
        EditarProductor = new javax.swing.JButton();
        EditarPais = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 450));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 450));
        jPanel1.setRequestFocusEnabled(false);

        menuButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuButton.setText("MENU");

        okButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        okButton.setText("OK");

        Lista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Lista);

        EditarNombrePelicula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditarNombrePelicula.setText("NOMBRE PELICULA");

        EditarPelicula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditarPelicula.setText("PELÍCULA");

        EditarDirector.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditarDirector.setText("DIRECTORES");

        EditarGenero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditarGenero.setText("GÉNEROS");

        EditarProductor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditarProductor.setText("PRODUCTORES");

        EditarPais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditarPais.setText("PAISES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditarProductor)
                            .addComponent(EditarPais))
                        .addGap(68, 83, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(EditarDirector)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditarGenero))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(EditarNombrePelicula)
                                .addGap(94, 94, 94)
                                .addComponent(EditarPelicula))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(menuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton)))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarProductor)
                    .addComponent(EditarDirector)
                    .addComponent(EditarGenero))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarPais)
                    .addComponent(EditarNombrePelicula)
                    .addComponent(EditarPelicula))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuButton)
                    .addComponent(okButton))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public class MENUButton implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e2) {
            MenuPrincipalFrame obj = new MenuPrincipalFrame();
            obj.setVisible(true);
            dispose();
        }

    }

    public class ListSelectionSub implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e7) {
            decision = Lista.getSelectedValue().toString();
        }

    }

    public class OKSub implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e6) {
            if (!variable.isEmpty() && !decision.isEmpty()){
            if (opc) {
                ProgramasExcel pex = new ProgramasExcel();
                try {
                    pex.peliculaExistente(variable, decision);
                } catch (IOException ex) {
                    Logger.getLogger(MenuEditarEliminar.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InvalidFormatException ex) {
                    Logger.getLogger(MenuEditarEliminar.class.getName()).log(Level.SEVERE, null, ex);
                }
                MenuEditarEliminar obj = new MenuEditarEliminar(true);
                obj.setVisible(true);        
                dispose();
                JOptionPane.showMessageDialog(jPanel1, variable + " eliminado correctamente", "Correcto", JOptionPane.INFORMATION_MESSAGE);
            } else {
                ProgramasExcel pex = new ProgramasExcel();
                boolean PerteneceNombreAHoja = false;
                try {
                    PerteneceNombreAHoja = pex.PerteneceNombreAHoja(VAR_PELICULA, decision);
                } catch (IOException ex) {
                    Logger.getLogger(MenuEditarEliminar.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InvalidFormatException ex) {
                    Logger.getLogger(MenuEditarEliminar.class.getName()).log(Level.SEVERE, null, ex);
                }

                if ((variable.equalsIgnoreCase(VAR_PELICULA)) && (PerteneceNombreAHoja)) {
                    AnadirEditarPeliculaCero obj = new AnadirEditarPeliculaCero(decision);
                    obj.setVisible(true);
                    dispose();
                } else {
                    EditarAnadirVariado obj = new EditarAnadirVariado(variable, decision);
                    obj.setVisible(true);
                    dispose();
                }
            }

        }else{
                JOptionPane.showMessageDialog(jPanel1, "Algun campo no ha sido seleccionado", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void rellenar() {
        ProgramasExcel pex = new ProgramasExcel();
        Lista.removeAll();
        try {
            String[] devolverNombres = pex.devolverNombres(variable);
            if (devolverNombres != null) {
                Lista.setListData(devolverNombres);
            }
        } catch (IOException ex) {
            Logger.getLogger(MenuEditarEliminar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidFormatException ex) {
            Logger.getLogger(MenuEditarEliminar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public class EditarNombrePeliculaSub implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e1) {

            variable = VAR_NOMBRE_PELICULA;
            rellenar();

        }

    }

    public class EditarGeneroSub implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e2) {

            variable = VAR_GENERO;
            rellenar();

        }

    }

    public class EditarDirectorSub implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e3) {
            variable = VAR_DIRECTOR;
            rellenar();

        }

    }

    public class EditarPaisSub implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e4) {
            variable = VAR_PAIS;
            rellenar();

        }

    }

    public class EditarProductorSub implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e5) {

            variable = VAR_PRODUCTOR;
            rellenar();

        }
    }

    public class EditarPeliculaSub implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e9) {

            variable = VAR_PELICULA;
            rellenar();

        }
    }

    private boolean opc;
    private static final String VAR_NOMBRE_PELICULA = "Nombre Pelicula";
    private static final String VAR_PELICULA = "Pelicula";
    private static final String VAR_GENERO = "Genero";
    private static final String VAR_DIRECTOR = "Director";
    private static final String VAR_PAIS = "Pais";
    private static final String VAR_PRODUCTOR = "Productor";
    private String decision;
    private String variable;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarDirector;
    private javax.swing.JButton EditarGenero;
    private javax.swing.JButton EditarNombrePelicula;
    private javax.swing.JButton EditarPais;
    private javax.swing.JButton EditarPelicula;
    private javax.swing.JButton EditarProductor;
    private javax.swing.JList<String> Lista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
