/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanels;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Juan
 */
public class MenuAnadirFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuAnadirFrame() {
        initComponents();
        Menu e1 = new Menu();
        Productor e2 = new Productor();
        Pelicula e3 = new Pelicula();
        Director e4 = new Director();
        Productor e5 = new Productor();
        Nombre_Pelicula e6 = new Nombre_Pelicula();
        Genero e7 = new Genero();
        MENUButton.addActionListener(e1);
        ANADIRProductor.addActionListener(e2);
        ANADIRPelicula.addActionListener(e3);
        ANADIRDirector.addActionListener(e4);
        ANADIRPais.addActionListener(e5);
        ANADIRNombrePelicula.addActionListener(e6);
        ANADIRGenero.addActionListener(e7);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MENUButton = new javax.swing.JButton();
        ANADIRNombrePelicula = new javax.swing.JButton();
        ANADIRPelicula = new javax.swing.JButton();
        ANADIRDirector = new javax.swing.JButton();
        ANADIRProductor = new javax.swing.JButton();
        ANADIRPais = new javax.swing.JButton();
        ANADIRGenero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 450));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(750, 450));

        MENUButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MENUButton.setText("MENU");

        ANADIRNombrePelicula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ANADIRNombrePelicula.setText("AÑADIR NOMBRE PELICULA");

        ANADIRPelicula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ANADIRPelicula.setText("AÑADIR PELICULA");

        ANADIRDirector.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ANADIRDirector.setText("AÑADIR DIRECTOR");

        ANADIRProductor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ANADIRProductor.setText("AÑADIR PRODUCTOR");

        ANADIRPais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ANADIRPais.setText("AÑADIR PAIS");

        ANADIRGenero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ANADIRGenero.setText("AÑADIR GENERO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MENUButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ANADIRNombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ANADIRPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ANADIRDirector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ANADIRProductor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ANADIRPais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ANADIRGenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ANADIRPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ANADIRNombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ANADIRDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(ANADIRProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ANADIRPais, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ANADIRGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(MENUButton)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private class Menu implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e1) {
            MenuPrincipalFrame obj = new MenuPrincipalFrame();
            obj.setVisible(true);
            dispose();
        }

    }

    private class Nombre_Pelicula implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e6) {
            opcion = "Nombre Pelicula";
            EditarAnadirVariado obj = new EditarAnadirVariado(opcion, "");
            obj.setVisible(true);
            dispose();
        }
    }

    private class Productor implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e2) {
            opcion = "Productor";
            EditarAnadirVariado obj = new EditarAnadirVariado(opcion, "");

            obj.setVisible(true);
            dispose();
        }
    }

    private class Pelicula implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e3) {
            AnadirPelicula obj = new AnadirPelicula();
            obj.setVisible(true);
            dispose();
        }
    }

    private class Director implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e4) {
            opcion = "Director";
            EditarAnadirVariado obj = new EditarAnadirVariado(opcion, "");
            obj.setVisible(true);
            dispose();
        }
    }

    private class Pais implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e5) {
            opcion = "Pais";
            EditarAnadirVariado obj = new EditarAnadirVariado(opcion, "");
            obj.setVisible(true);
            dispose();
        }
    }

    private class Genero implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e7) {
            opcion = "Genero";
            EditarAnadirVariado obj = new EditarAnadirVariado(opcion, "");
            obj.setVisible(true);
            dispose();
        }
    }

    private String opcion;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANADIRDirector;
    private javax.swing.JButton ANADIRGenero;
    private javax.swing.JButton ANADIRNombrePelicula;
    private javax.swing.JButton ANADIRPais;
    private javax.swing.JButton ANADIRPelicula;
    private javax.swing.JButton ANADIRProductor;
    private javax.swing.JButton MENUButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
